#!/usr/bin/env bash
# 现场主从 IP 默认值（source 后可用环境变量覆盖）
EXCAVATOR_SLAVE_IP="${EXCAVATOR_SLAVE_IP:-192.168.31.170}"
EXCAVATOR_GATEWAY_PORT="${EXCAVATOR_GATEWAY_PORT:-8765}"
EXCAVATOR_CONTROL_PORT="${EXCAVATOR_CONTROL_PORT:-8766}"
EXCAVATOR_ROS_DOMAIN_ID="${EXCAVATOR_ROS_DOMAIN_ID:-42}"

# 主端：连从端 gateway 与 ROS2 DDS peer
excavator_apply_host_network_defaults() {
  export EXCAVATOR_BRIDGE_HOST="${EXCAVATOR_BRIDGE_HOST:-${EXCAVATOR_SLAVE_IP}}"
  export EXCAVATOR_ROS_PEER_IP="${EXCAVATOR_ROS_PEER_IP:-${EXCAVATOR_SLAVE_IP}}"
}

# 从端：本机 bridge / gateway
excavator_apply_slave_network_defaults() {
  export EXCAVATOR_BRIDGE_HOST="${EXCAVATOR_BRIDGE_HOST:-127.0.0.1}"
  export EXCAVATOR_CONTROL_HOST="${EXCAVATOR_CONTROL_HOST:-127.0.0.1}"
  export EXCAVATOR_GATEWAY_HOST="${EXCAVATOR_GATEWAY_HOST:-0.0.0.0}"
}
